# Generated by Django 4.1.2 on 2023-01-21 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('initial_deposit', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UtangPiutang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('person_in_charge', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('U', 'Utang'), ('P', 'Piutang')], max_length=1)),
                ('nominal', models.PositiveBigIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pelaku', models.CharField(blank=True, max_length=30, null=True)),
                ('trc_name', models.CharField(max_length=50)),
                ('price', models.PositiveBigIntegerField()),
                ('trc_type', models.IntegerField(choices=[(1, 'Kredit'), (-1, 'Debit')])),
                ('trc_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isTransfer', models.BooleanField(blank=True, default=False, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keuangan.kategori')),
                ('pelunasan_utangpiutang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.utangpiutang')),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.rekening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
