# Generated by Django 4.1.2 on 2022-10-18 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('isHidden', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('saldo_awal', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keuangan.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('tanngal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtangPiutang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jatuh_tempo', models.DateTimeField(default=django.utils.timezone.now)),
                ('pelaku', models.CharField(blank=True, max_length=30, null=True)),
                ('tipe', models.CharField(choices=[('U', 'Utang'), ('P', 'Piutang')], max_length=1)),
                ('nominal', models.PositiveBigIntegerField(default=0)),
                ('isLunas', models.BooleanField(default=False)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keuangan.kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pelaku', models.CharField(blank=True, max_length=30, null=True)),
                ('nama_transaksi', models.CharField(max_length=50)),
                ('harga', models.PositiveBigIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('tipe', models.IntegerField(choices=[(1, 'Pendapatan'), (-1, 'Pengeluaran')])),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.akun')),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keuangan.kategori')),
                ('pelunasan_utangpiutang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.utangpiutang')),
                ('transfer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keuangan.transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
